openapi: 3.1.0
x-stoplight:
  id: po6s4rnul4zy6
info:
  title: API仕様書-PH2-即時充電
  version: '1.0'
  contact:
    name: N'S Creates .inc
  termsOfService: CEL-Project
  description: フェーズ2で使用するAPI
servers:
  - url: 'http://localhost:3000'
paths:
  /api/spot-charge/status-info:
    get:
      summary: 即時充電-ステータス情報取得
      tags:
        - SPOT-CHARGE
        - PH1.5
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: ステータス
                  disableFlg:
                    type: boolean
                    description: 使用可不可フラグ
                  chargingInfo:
                    type:
                      - object
                      - 'null'
                    properties:
                      chargeOrderId:
                        type: integer
                        description: 充電注文ID
                      shopName:
                        type: string
                        description: 店舗名
                      connectorName:
                        type: string
                        description: 充電場所
                      chargingTime:
                        type:
                          - integer
                          - 'null'
                        description: 経過時間
                      chargingPrice:
                        type:
                          - integer
                          - 'null'
                        description: 料金
                      chargingStatus:
                        type:
                          - integer
                          - 'null'
                        description: 充電残量
                    required:
                      - chargeOrderId
                      - shopName
                      - connectorName
                required:
                  - status
                  - disableFlg
              examples:
                Example-通常時:
                  value:
                    status: 0
                    disableFlg: false
                    chargingInfo: null
                Example-通常時-ボタン使用不可:
                  value:
                    status: 0
                    disableFlg: true
                    chargingInfo: null
                Example-待機中:
                  value:
                    status: 1
                    disableFlg: true
                    chargingInfo:
                      chargeOrderId: 1
                      shopName: イオン茨城店
                      connectorName: 東3
                      chargingTime: null
                      chargingPrice: null
                      chargingStatus: null
                Example-充電中:
                  value:
                    status: 2
                    disableFlg: true
                    chargingInfo:
                      chargeOrderId: 2
                      shopName: イオン茨城店
                      connectorName: 東3
                      chargingTime: 40
                      chargingPrice: 1200
                      chargingStatus: 65
                Example-充電中(普通充電):
                  value:
                    status: 2
                    disableFlg: true
                    chargingInfo:
                      chargeOrderId: 2
                      shopName: イオン茨城店
                      connectorName: 東3
                      chargingTime: 40
                      chargingPrice: 1200
                      chargingStatus: null
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error202'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
      operationId: get-api-charge-statusInfo
      description: |-
        【利用場面】

        https://projects.invisionapp.com/share/C9134J2ZJU2R#/screens/471406861
        https://projects.invisionapp.com/share/C9134J2ZJU2R#/screens/471406869
        https://projects.invisionapp.com/share/C9134J2ZJU2R#/screens/471413902
    parameters: []
  /api/spot-charge/collation:
    post:
      summary: 即時充電-チャージャ照合
      tags:
        - SPOT-CHARGE
        - PH1.5
      operationId: post-api-charger-collation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  chargerId:
                    type: integer
                    description: チャージャID
                required:
                  - chargerId
              examples:
                Example 1:
                  value:
                    chargerId: 1
                    connectorId: 1
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error202'
              examples:
                Example 1:
                  value:
                    status: 202
                    title: QR読み込み
                    msg: Q対象のチャージャは使用できません。
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
      description: |-
        【利用場面】

        https://projects.invisionapp.com/share/C9134J2ZJU2R#/screens/471406863
        https://projects.invisionapp.com/share/C9134J2ZJU2R#/screens/471406864
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: QRのtoken
                  example: Avddfad4f4dfasdsf4d654f
              required:
                - token
            examples:
              Example 1:
                value:
                  token: Avddfad4f4dfasdsf4d654f
    parameters: []
  '/api/spot-charge/chargers/{chargerId}':
    parameters:
      - schema:
          type: string
        name: chargerId
        in: path
        required: true
    get:
      summary: 即時充電-チャージャ情報取得
      tags:
        - SPOT-CHARGE
        - PH1.5
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  chargeLimitHour:
                    type:
                      - integer
                      - 'null'
                    description: 最大充電可能時間
                  balancePoint:
                    type: integer
                    description: ポイント残高
                  shopName:
                    type: string
                    description: 利用店舗
                  connectorId:
                    type: integer
                    description: コネクタID
                  connectorName:
                    type: string
                    description: 充電場所
                  chargerTypeName:
                    type: string
                    description: 充電タイプ
                  chargerOutlet:
                    type: string
                    description: 差込口タイプ
                  chargerOutputName:
                    type: string
                    description: 充電出力名
                  chargeUnitPriceStr:
                    type: string
                    description: 充電単価名
                  chargerImageUrl:
                    type: string
                    description: 画像URL
                  demandType:
                    type:
                      - integer
                      - 'null'
                    description: デマンドタイプ
                  chargerWaitFlag:
                    type: boolean
                    description: 待機フラグ
                required:
                  - balancePoint
                  - shopName
                  - connectorId
                  - connectorName
                  - chargerTypeName
                  - chargerOutlet
                  - chargerOutputName
                  - chargeUnitPriceStr
                  - chargerImageUrl
                  - chargerWaitFlag
              examples:
                Example-待ち時間あり:
                  value:
                    chargeLimitHour: 7
                    balancePoint: 2000
                    shopName: イオン茨木店
                    connectorId: 1
                    connectorName: 東P3番
                    chargerTypeName: 普通
                    chargerOutlet: CHAdeMO
                    chargerOutputName: 3kW～6kW
                    chargeUnitPriceStr: 20円/分
                    chargerImageUrl: 'https://webapp.cleanenergylabo.jp/storage/chargers/default1.png'
                    demandType: 2
                    chargerWaitFlag: true
                Example-待ち時間なし:
                  value:
                    chargeLimitHour: 7
                    balancePoint: 2000
                    shopName: イオン茨木店
                    connectorId: 1
                    connectorName: 東P3番
                    chargerTypeName: 普通
                    chargerOutlet: CHAdeMO
                    chargerOutputName: 3kW
                    chargeUnitPriceStr: 20円/分
                    chargerImageUrl: 'https://webapp.cleanenergylabo.jp/storage/chargers/default1.png'
                    demandType: null
                    chargerWaitFlag: false
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
      operationId: get-api-ph2-charge-info
      description: |-
        【利用場面】

        https://projects.invisionapp.com/share/C9134J2ZJU2R#/screens/471406864
        https://projects.invisionapp.com/share/C9134J2ZJU2R#/screens/471406865
        https://projects.invisionapp.com/share/C9134J2ZJU2R#/screens/471406867
        https://projects.invisionapp.com/share/C9134J2ZJU2R#/screens/471413897
        https://projects.invisionapp.com/share/C9134J2ZJU2R#/screens/471413901
      parameters: []
  /api/spot-charge/start:
    post:
      summary: 即時充電-充電スタート
      tags:
        - SPOT-CHARGE
        - PH1.5
      operationId: post-api-ph2-charger-start
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              examples:
                Example 1:
                  value: {}
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error202'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
      description: |-
        【利用場面】

        https://projects.invisionapp.com/share/C9134J2ZJU2R#/screens/471406867
        https://projects.invisionapp.com/share/C9134J2ZJU2R#/screens/471413901
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                chargerId:
                  type: integer
                  description: チャージャID
                connectorId:
                  type: integer
                  description: コネクタID
                usePoint:
                  type:
                    - integer
                    - 'null'
                  description: 利用ポイント
              required:
                - chargerId
                - connectorId
            examples:
              Example 1:
                value:
                  chargerId: 1
                  connectorId: 1
                  usePoint: 200
    parameters: []
  /api/spot-charge/stop:
    post:
      summary: 即時充電-充電ストップ
      tags:
        - SPOT-CHARGE
        - PH1.5
      operationId: post-api-charge-stop
      description: |-
        【利用場面】

        https://projects.invisionapp.com/share/C9134J2ZJU2R#/screens/471406871
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                chargeOrderId:
                  type: integer
                  description: チャージャID（充電注文ID）
              required:
                - chargeOrderId
            examples:
              Example 1:
                value:
                  chargeOrderId: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
    parameters: []
  /api/spot-charge/wait-cancel:
    post:
      summary: 即時充電-待機取消
      tags:
        - SPOT-CHARGE
        - PH1.5
      operationId: post-api-spot-charge-wait-cancel
      description: |-
        【利用場面】

        https://projects.invisionapp.com/share/C9134J2ZJU2R#/screens/471413903
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                chargeOrderId:
                  type: integer
                  description: 充電注文ID
              required:
                - chargeOrderId
            examples:
              Example 1:
                value:
                  chargeOrderId: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
    parameters: []
  '/api/spot-charge/{orderId}/charging-status':
    get:
      summary: 即時充電-充電中情報取得
      operationId: get-api-charge-charging-status
      tags:
        - SPOT-CHARGE
        - PH1.5
      description: |-
        【利用場面】

        https://projects.invisionapp.com/share/C9134J2ZJU2R#/screens/471406870
        https://projects.invisionapp.com/share/C9134J2ZJU2R#/screens/471413903
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: ステータス
                  chargerImageUrl:
                    type: string
                    description: チャージャ画像URL
                  shopName:
                    type: string
                    description: 店舗名
                  connectorName:
                    type: string
                    description: 充電場所
                  chargerOutlet:
                    type: string
                    description: 差込口タイプ
                  chargerOutputName:
                    type:
                      - string
                      - 'null'
                    description: 経過出力
                  chargingTime:
                    type:
                      - integer
                      - 'null'
                    description: 経過時間
                  chargingPrice:
                    type:
                      - integer
                      - 'null'
                    description: 経過料金
                  chargingUnitPrice:
                    type:
                      - integer
                      - 'null'
                    description: 経過単価
                  usePoint:
                    type:
                      - integer
                      - 'null'
                    description: ポイント利用
                  demandType:
                    type:
                      - integer
                      - 'null'
                    description: デマンドタイプ
                required:
                  - status
                  - chargerImageUrl
                  - shopName
                  - connectorName
                  - chargerOutlet
                  - chargerOutputName
              examples:
                Example-待機中:
                  value:
                    status: 1
                    chargerImageUrl: 'https://webapp.cleanenergylabo.jp/storage/chargers/default1.png'
                    shopName: イオン茨木店
                    connectorName: 東P3
                    chargerOutlet: CHAdeMO
                    chargerOutputName: 3kW
                    chargingTime: null
                    chargingPrice: null
                    chargingUnitPrice: null
                    usePoint: null
                    demandType: 1
                Example-充電中:
                  value:
                    status: 2
                    chargerImageUrl: 'https://webapp.cleanenergylabo.jp/storage/chargers/default1.png'
                    shopName: イオン茨木店
                    connectorName: 東P3
                    chargerOutlet: CHAdeMO
                    chargerOutputName: 3kW
                    chargingTime: 75
                    chargingPrice: 4500
                    chargingUnitPrice: 60
                    usePoint: 0
                    demandType: null
                Example-デマンド機能:
                  value:
                    status: 2
                    chargerImageUrl: 'https://webapp.cleanenergylabo.jp/storage/chargers/default1.png'
                    shopName: イオン茨木店
                    connectorName: 東P3
                    chargerOutlet: CHAdeMO
                    chargerOutputName: 3kW～6Kw
                    chargingTime: 75
                    chargingPrice: 4500
                    chargingUnitPrice: 60
                    usePoint: 230
                    demandType: 2
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
      parameters: []
    parameters:
      - schema:
          type: integer
        name: orderId
        in: path
        required: true
        description: チャージャID（充電注文ID）
components:
  schemas:
    Error:
      type: object
      title: Error
      description: エラーオブジェクトの共通スキーマ
      properties:
        status:
          type: integer
        msg:
          type: string
        '':
          type: string
    Error202:
      type: object
      title: Error202
      description: エラーオブジェクトの共通スキーマ
      properties:
        status:
          type: integer
          example: 202
        title:
          type: string
          example: タイトル
        msg:
          type: string
          example: メッセージ
      required:
        - title
        - status
        - msg
      examples:
        - status: 202
        - title: タイトル
        - msg: メッセージ
    Error401:
      type: object
      title: Error401
      description: エラーオブジェクトの共通スキーマ
      x-stoplight:
        id: 310afb0d95362
      examples:
        - status: 401
          msg: Unauthorized
      properties:
        status:
          type: integer
          example: 401
        msg:
          type: string
          example: Unauthorized
      required:
        - status
        - msg
    Error403:
      type: object
      title: Error403
      description: エラーオブジェクトの共通スキーマ
      examples:
        - status: 403
          msg: Forbidden
      properties:
        status:
          type: integer
          example: 403
        msg:
          type: string
          example: Forbidden
      required:
        - status
        - msg
      x-stoplight:
        id: cf5616fdbf55a
    Error500:
      type: object
      title: Error500
      description: エラーオブジェクトの共通スキーマ
      examples:
        - status: 500
          msg: Internal Server Error
      properties:
        status:
          type: integer
          example: 500
        msg:
          type: string
          example: Internal Server Error
      required:
        - status
        - msg
      x-stoplight:
        id: c3489106265bf
  securitySchemes:
    MEMBER-TOKEN:
      type: http
      scheme: bearer
tags:
  - name: Owner
    description: Ownerに関する API 群です
  - name: SPOT-CHARGE
    description: Ownerに関する API 群です
  - name: PH1.5
    description: 1.5で実装する API 群です
  - name: PH2.0
    description: 2.0で実装する API 群です
